const tabs = require("./common/tabs.js");
const speakers = require("./speakers/speaker.js");
const slider = require("./slider/slider.js");
const firstScreen = require("./common/firstScreen");
const tabsProgram = require("./common/tabsProgram");
// const modalAnimation = require("./common/modalAnimation");
const fancybox = require("@fancyapps/fancybox");
const popup = require("./common/popup");
const cta = require("./common/actPopup");
const rightMenu = require("./common/rightMenu");
const ticketBuy = require("./common/ticketBuy");
const regPhone = require("./common/regPhone");
// const clickForm = require("./reg/clickForm");
const recommendation = require("./recommendation/recommendation");
const bundleWishlist = require("./wishlist/bundleWishlist");
const btnUp = require("./common/btnUp");
const header = require("./common/header");
// clickForm();
rightMenu();
cta();
popup();
ticketBuy();
speakers();
slider();
tabs();
firstScreen();
tabsProgram();
// modalAnimation();
regPhone();
recommendation();
bundleWishlist();
btnUp();
header();
